name: Dashify
main: io.dashify.plugin.DashifyPluginMain
version: 0.0.1
api-version: '1.19'

authors: [ pybsh , aroxu ]

commands:
  dashify:
    usage: /dashify [ key | enable | disable ]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21
  - org.mindrot:jbcrypt:0.4
  - io.ktor:ktor-server-core-jvm:2.3.1
  - io.ktor:ktor-server-cors-jvm:2.3.1
  - io.ktor:ktor-server-jetty-jvm:2.3.1
  - io.ktor:ktor-server-content-negotiation-jvm:2.3.1
  - io.ktor:ktor-serialization-jackson-jvm:2.3.1
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0
