name: Dashify
main: io.dashify.plugin.DashifyPluginMain
version: 0.0.1
api-version: '1.19'

authors: [ pybsh , aroxu ]

commands:
  dashify:
    usage: /dashify [ key | enable | disable ]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21
  - org.mindrot:jbcrypt:0.4
